### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by ThisIzEthan** [DragonetMC/LegendaryNations#1]
```
    @Override
    public void onDisable() {
        instance = null;
    }
```
Normally this is for data saving operations/logging that the plugin is disabled. Why make instance null when the garbage collector will do it once the plugin disables?

**Comment by DefinitlyEvil** [comment]
just to make sure it clears nvm I will add more code to that method ;)

**Comment by ThisIzEthan** [comment]
Okay :P
